"""add avatar to teachers

Revision ID: 43808c0a919d
Revises: 
Create Date: 2025-09-15 15:13:13.881369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43808c0a919d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###
